### ISSUE TITLE
Crash when clicking on equalizer when track is playing

### ISSUE THREAD

**Issue by RomanKarwacik** [iamSahdeep/Bop#16]
**Describe the bug**
When I click in the PlayerVIew on the equalizer button while a track is playing, the app crashes. When the track is paused and I click the button, it does not crash.  
Relevant Logcat:
```
[01-31 13:20:06.159 543:543 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.sahdeepsingh.Bop, PID: 543
java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation
	at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1273)
	at android.media.audiofx.BassBoost.setProperties(BassBoost.java:285)
	at com.sahdeepsingh.Bop.equalizer.a.f(Unknown Source)
	at androidx.fragment.app.c.k(Unknown Source)
	at androidx.fragment.app.j.a(Unknown Source)
	at androidx.fragment.app.o.a(Unknown Source)
	at androidx.fragment.app.o.a(Unknown Source)
	at androidx.fragment.app.o.a(Unknown Source)
	at androidx.fragment.app.j.a(Unknown Source)
	at androidx.fragment.app.j.b(Unknown Source)
	at androidx.fragment.app.j.g(Unknown Source)
	at androidx.fragment.app.j$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Smartphone (please complete the following information):**
 - Device: Moto G4
 - OS: Android 7.1 (Lineage OS 15.1)
 - Version 1.0 (FDroid)

**Comment by iamSahdeep** [comment]
Hey, i tried to reproduce the problem on several devices and all are working fine. Also in log cat the source is unknown which makes it difficult to find the root. Can you tell me if it is not working on your other devices also?

**Comment by RomanKarwacik** [comment]
I don't have any other devices currently, but it might have to do with using a custom rom: https://stackoverflow.com/a/51918073  
This fixed it, but I'm no Android developer, so I don't know if it should always be called OnCreate, or if it will affect other phones differently. Here is my branch where I changed it: https://github.com/RomanKarwacik/Bop/commit/cbbdf65a1a2c4e611239130e7154ac1d1389c8d8

**Comment by iamSahdeep** [comment]
I have tested your branch and its working fine and not effecting other devices. Also as answer suggested to enable the custom equalizer first, i have commented on your commit about it. 
You can make PR with and i will merge it.
