### ISSUE TITLE
Scrolling through Genres/Albums/Songs/Artists very slow

### ISSUE THREAD

**Issue by RomanKarwacik** [iamSahdeep/Bop#17]
I have a very big library on my phone, and every category is very laggy and slow to navigate, making it nearly unusable, often times leading to OutOfMemory errors. Here is a demonstration: https://streamable.com/f97af  
And the outofmemory:
```
[01-31 13:43:05.409 3661:3661 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.sahdeepsingh.Bop, PID: 3661
java.lang.OutOfMemoryError: Failed to allocate a 2560012 byte allocation with 2214568 free bytes and 2MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:660)
	at android.provider.MediaStore$Images$Media.getBitmap(MediaStore.java:873)
	at com.sahdeepsingh.Bop.b.a.b(Unknown Source)
	at com.sahdeepsingh.Bop.b.a.a(Unknown Source)
	at com.sahdeepsingh.Bop.a.h.a(Unknown Source)
	at com.sahdeepsingh.Bop.a.h.a(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView$a.a(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView$a.b(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView$p.a(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView$p.a(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView$p.a(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView$p.c(Unknown Source)
	at androidx.recyclerview.widget.LinearLayoutManager$c.a(Unknown Source)
	at androidx.recyclerview.widget.LinearLayoutManager.a(Unknown Source)
	at androidx.recyclerview.widget.LinearLayoutManager.a(Unknown Source)
	at androidx.recyclerview.widget.LinearLayoutManager.c(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView.O(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView.r(Unknown Source)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at androidx.viewpager.widget.ViewPager.onLayout(Unknown Source)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at com.google.android.material.appbar.b.b(Unknown Source)
	at com.google.android.material.appbar.c.a(Unknown Source)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.a(Unknown Source)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(Unknown Source)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17641)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
```

**Smartphone (please complete the following information):**
 - Device: Moto G4
 - OS: Android 7.1 (Lineage OS 15.1)
 - Version 1.0 (FDroid)

**Comment by iamSahdeep** [comment]
Hi @RomanKarwacik thanks for pointing error and possible bugs. The error is the result of loading lots of bitmaps in recyclerview which makes the scrolling slow or laggy and sometimes outofmemory exception is thrown.I haven't found the possible way to load images properly but will try to solve it by researching more. Thanks :)

**Comment by iamSahdeep** [comment]
yup u r right. That loop to find the cover is causing the lag. I have also made some changes to app same time in dev  [branch](https://github.com/iamSahdeep/Bop/commit/dbb9ec7dda23ea3ad3f4b3ca42a7fafbc0af1660)

**Comment by RomanKarwacik** [comment]
It is still very slow (no notable improvement).  
You can't use the URI as a path, as it has to be handled by the ContentResolver first.  
In getAlbumArt, both getting the Bitmap and the path from the cursor takes a considerably long time, (about 200ms), where you would only need the URI, or the resolved path.

**Comment by iamSahdeep** [comment]
Alright, you can make PR with your changes. i will delete this branch. And thanks for contributing. :100:

**Comment by RomanKarwacik** [comment]
I wouldn't want my changes, as I didn't make it modular and the SongsRecyclerAdapter doesn't have the album cover after selecting a song.

**Comment by iamSahdeep** [comment]
That's because the song is always checked, in onBindView for selected or not 
`if (selected.contains(localItem))
            highlightView(holder);
        else
            unhighlightView(holder, bitmap);`
and you have just created an empty bitmap.
You can make PR anyway, I will solve the issue
