### ISSUE TITLE
The app crashed when I played a genre or an album, played the next song on the album, and then when back to play another different album. 

### ISSUE THREAD

**Issue by HarryHeights** [iamSahdeep/Bop#34]
**Describe the bug**
On the app, I can play an album or genre of music. When I click on a genre of music, or a music album, it automatically plays all the song in that collection. I accessed the music navigation page where I can pause a track, rewind/fast-forward a track or play the next track on queue. 
I noticed that after I played the next track by clicking on the appropriate button, and went back to try to play another genre/album; the app crashed. 

**To Reproduce**
- Launch app
- Access options menu
- Goto either genres page or album page.
- Open an album or genre with at least 2 songs in it.
- Play the genre/album by clicking on it
- On the now playing screen, tap on the music note icon to open music navigation page. (The icon is on the right side of the app)
- On the music navigation page; Click the button to play next track
- After the next track is Now playing; go back to the main album/genre list
- Click on any other genre/album
- See error. (The app will crash). 

**Expected behavior**
I expected that I could play any music album or genre of music at any time I desired. Even after performing some other actions on the app, like playing the next track on a previous album/genre I was on. 

**Screen recording**

**Test Environment**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Software version: Bop music player v1.1.2

**Additional context**
Here's the logcat from the crash;

``` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sahdeepsingh.Bop/com.sahdeepsingh.Bop.Activities.PlayingNowList}: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.sahdeepsingh.Bop.services.ServicePlayMusic.h(Unknown Source:16)
	at com.sahdeepsingh.Bop.Activities.PlayingNowList.onCreate(Unknown Source:193)
	at android.app.Activity.performCreate(Activity.java:7084)
	at android.app.Activity.performCreate(Activity.java:7075)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
	... 9 more
```

**Comment by iamSahdeep** [comment]
I am able to reproduce it, thanks . Will look for it soon.

**Comment by HarryHeights** [comment]
Okay no qualms. I love how you respond very quickly to issues. It shows you are passionate about maintaining this app and delivering the best user experience as possible. I would love to write about the app on my blog. I hope that is okay by you?

**Comment by iamSahdeep** [comment]
Yeah, Its totally fine from my side. I would love to see your blogs, drop me a link anytime. 
I have just started it as an "Android Learning Project" but now working on it makes me more passionate about OS and Development.

**Comment by HarryHeights** [comment]
Okay. I will do that as soon as I create a blog.
