### ISSUE TITLE
Don't able to play songs from file manager

### ISSUE THREAD

**Issue by sagorahmed** [iamSahdeep/Bop#38]
**Describe the bug**
The app is crashing when I try to play music from the file manager. 

**To Reproduce**
1. Go to your phone's default file manager.
2. Choose a music file
3. Then open that file with Bop music player

**Expected behavior**
I expected that I can play my desired song from the file manager using this music player without getting any trouble.

**Screenshots**
https://www.youtube.com/watch?v=0BBHeGL1dag

**Informations**
 - Device: Samsung a5
 - OS: 6.0.1
 - Version: Bop music player v1.2

**Additional context**
Logcat
```
03-22 17:55:06.460 11309 11309 D AndroidRuntime: Shutting down VM

03-22 17:55:06.460 11309 11309 E AndroidRuntime: FATAL EXCEPTION: main

03-22 17:55:06.460 11309 11309 E AndroidRuntime: Process: com.sahdeepsingh.Bop, PID: 11309

03-22 17:55:06.460 11309 11309 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=6; regionStart=0; regionLength=-1

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at java.lang.String.startEndAndLength(String.java:298)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at java.lang.String.substring(String.java:1087)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at com.sahdeepsingh.Bop.c.a.a(Unknown Source)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at com.sahdeepsingh.Bop.Activities.SplashScreen$a.a(Unknown Source)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at com.sahdeepsingh.Bop.Activities.SplashScreen$a.onPostExecute(Unknown Source)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

03-22 17:55:06.460 11309 11309 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by iamSahdeep** [comment]
The issue is occurring some of the devices. I will work on soon, would take some time. Thanks for reporting.

**Comment by sagorahmed** [comment]
Thanks for your quick response.

**Comment by sagorahmed** [comment]
So sorry for closing the issue mistakenly

**Comment by iamSahdeep** [comment]
hey @sagorahmed  can you check the latest issue and tell me if its working or not,   [v1.2.1](https://github.com/iamSahdeep/Bop/releases/tag/v1.2.1)

**Comment by sagorahmed** [comment]
This issue is still there. This time it's not crashing but can't be playing the songs from the file manager. 
![problem](https://media.giphy.com/media/S9j5AybXIoIW1OBDhV/giphy.gif)

**Comment by pokulo** [comment]
I am confused, because I cant make it play some songs. They do not get scanned and I can't simply select a Song/Album/Playlist/Folder from within the player and just play my favorite music, instead the player refuses to play songs that are not scanned!? Weird reason, because all other players I know simply play a music file when selected. Please repair, otherwise I will trash this app again. Thanks.
