### ISSUE TITLE
The application crashes and cannot be used again when playing music files that have been deleted

### ISSUE THREAD

**Issue by ahyar92** [iamSahdeep/Bop#39]
**Describe the bug**
When I tried playing one of the music in the application, I accidentally deleted the music that I played in the file manager. Then I returned to the album page and played another music. And I see the music files that I have deleted are still available on the Album page. Then I tried clicking the music file that I deleted earlier. Suddenly the application crashes and exits by itself. Then I tried to reopen the application but it couldn't and the crash continued. So I have to restart the application.

**To Reproduce**
1. Install and open the application
2. Then go to the album page and play one of the music
3. Next, enter the file manager page and delete the music you are playing
4. Then go back to the application and enter the album page again, then you will see the deleted file still exists and is still playing.
4. Then play another song, and then click on the music file that you deleted earlier.
5. then the error will be seen

**Expected behavior**
Supposedly, when I play deleted music files there will be no crashes. Supposedly, when a user plays a deleted file, a short message will appear like "File not found".

**Recording Of The Bug**
https://youtu.be/ojSssTzUOdg

**Environment**
Tested on 2 devices:

<table>
<thead>
<tr><th>Device</th><th>Android Version</th>
</thead>
<tbody>
<tr><td>VIVO Y81</td><td>Oreo 8.1.0 (CPU: Octa-core Max 2.0 GHz, RAM: 3 GB)</td>
<tr><td>Realmi U1</td><td>Oreo 8.1.0 (Octa-core (4x2.1 GHz Cortex-A73 & 4x2.0 GHz Cortex-A53, RAM: 4 GB)</td>
</table>

## Logcat
``` --------- beginning of crash
03-23 21:46:18.147  7424  7424 E AndroidRuntime: FATAL EXCEPTION: main
03-23 21:46:18.147  7424  7424 E AndroidRuntime: Process: com.sahdeepsingh.Bop, PID: 7424
03-23 21:46:18.147  7424  7424 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.sahdeepsingh.Bop.c.c.b()' on a null object reference
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at com.sahdeepsingh.Bop.g.b.a(Unknown Source:6)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at com.sahdeepsingh.Bop.services.ServicePlayMusic.w(Unknown Source:15)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at com.sahdeepsingh.Bop.services.ServicePlayMusic.h(Unknown Source:79)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at com.sahdeepsingh.Bop.a.c$1.onClick(Unknown Source:13)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at android.view.View.performClick(View.java:6325)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25098)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:192)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6779)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
03-23 21:46:18.147  7424  7424 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)
03-23 21:46:18.154  1432  1943 D SLService: ppCra : com.sahdeepsingh.Bop pid : 7424```

**Comment by iamSahdeep** [comment]
Thanks @ahyar92 for reporting issue, I might need to look for possibilities to prevent this scenario. Will look soon into it.

**Comment by ahyar92** [comment]
You're welcome sir :)
